# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Foresight CI Lab

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
  
    runs-on: ubuntu-latest

    #strategy:
    #  matrix:
    #    node-version: [12.x, 14.x, 16.x, 18.x]
    # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    
    steps:
      - name: Collect Workflow Telemetry
        uses: runforesight/foresight-workflow-kit-action@v1
        with:
          api_key: ${{ secrets.FRS_LAB_API_KEY }}
      - name: Checkout
        uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - name: Print NPM version
        run: |
          npm --version    
      - name: Run script
        run: |
          cd scripts && chmod +x ./run.sh && ./run.sh
      - run: npm ci
      - run: npm run build --if-present
      - name: run tests
        run: HEADLESS=true npm test --coverage
      - name: Foresight 
        if: success() || failure()
        uses: runforesight/foresight-test-kit-action@v1
        with:
          api_key: ${{ secrets.FRS_LAB_API_KEY }}
          test_format: JUNIT
          test_framework: JEST
          test_path: ./junit.xml   
          coverage_format: COBERTURA/XML
          coverage_path: coverage/*.xml
