# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x, 18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - name: Collect Workflow Telemetry
      uses: thundra-io/workflow-telemetry-action@feature/file-tracer
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: Run script
      run: |
        chmod +x ./run.sh && ./run.sh
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test --coverage
    - name: Foresight Upload a Build Artifact
      if: success() || failure()
      uses: actions/upload-artifact@v3.1.0
      with:
       name: test-result-jest
       path: ./junit.xml   
    - name: Archive coverage results
      uses: actions/upload-artifact@v2
      if: success() || failure()
      with:
        name: coverage-artifact
        path: coverage/*.xml  
       
